import { type NextPage } from "next";
import Head from "next/head";
import Calendar from "~/components/Calendar";
import styles from "~/styles/prenota.module.css";

const Prenota: NextPage = () => {

  return (
    <>
      <Head>
        <title>Terrarossa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.main}>
          <Calendar />
        </div>
    </>
  );
};

export default Prenota;
