#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# lint
npx pretty-quick --staged

# remove `.only` from tests under `/cypress`
# note that '' after `sed -i` is required only for macOS
find ./cypress -type f \( -name "*.cy.ts" -o -name "*.cy.tsx" \) -exec sed -i '' 's/\.only(/(/g' {} +