# keep name short as it is displayed in readme badge
name: Cypress CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
env:
  NODE_ENV: "test" # see: https://github.com/vercel/next.js/issues/55804#issuecomment-1735124191.
  NEXT_PUBLIC_APP_ENV: "test"
  DEBUG: "cypress:server:args"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TURSO_DATABASE_URL: "file:./prisma/dev.db"
  NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
  NEXTAUTH_URL: ${{vars.NEXTAUTH_URL}}
  AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
  AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
  AUTH0_ISSUER: ${{vars.AUTH0_ISSUER}}
  AUTH0_BASE_URL: ${{vars.AUTH0_BASE_URL}}
  CYPRESS_ADMIN_FORO_MAIL: ${{secrets.CYPRESS_ADMIN_FORO_MAIL}}
  CYPRESS_ADMIN_FORO_PWD: ${{secrets.CYPRESS_ADMIN_FORO_PWD}}
  CYPRESS_ADMIN_ALLENGLAND_MAIL: ${{secrets.CYPRESS_ADMIN_ALLENGLAND_MAIL}}
  CYPRESS_ADMIN_ALLENGLAND_PWD: ${{secrets.CYPRESS_ADMIN_ALLENGLAND_PWD}}
  CYPRESS_USER1_MAIL: ${{secrets.CYPRESS_USER1_MAIL}}
  CYPRESS_USER1_PWD: ${{secrets.CYPRESS_USER1_PWD}}
  CYPRESS_USER2_MAIL: ${{secrets.CYPRESS_USER2_MAIL}}
  CYPRESS_USER2_PWD: ${{secrets.CYPRESS_USER2_PWD}}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  NEXT_PUBLIC_LOGFLARE_API_KEY: ${{ secrets.NEXT_PUBLIC_LOGFLARE_API_KEY }}
  NEXT_PUBLIC_LOGFLARE_SOURCE_ID: ${{ secrets.NEXT_PUBLIC_LOGFLARE_SOURCE_ID }}
  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
  NEXT_PUBLIC_R2_BUCKET_NAME: ${{ vars.NEXT_PUBLIC_R2_BUCKET_NAME }}
  NEXT_PUBLIC_R2_BUCKET_URL: ${{ vars.NEXT_PUBLIC_R2_BUCKET_URL }}

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          build: pnpm build:test
          runTests: false
      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: .next
          include-hidden-files: true

  ui-chrome-tests:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .next
      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v5
        with:
          # use build step to seed the database, build is already done in install job
          build: npm run db:seed
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          config-file: cypress.config.ts

  ui-chrome-mobile-tests:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .next
      - name: "UI Tests - Chrome - Mobile"
        uses: cypress-io/github-action@v5
        with:
          config: "viewportWidth=375,viewportHeight=667"
          #use build step to seed the database, build is already done in install job
          build: pnpm run db:seed
          start: pnpm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          config-file: cypress.config.ts

  component-testing:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .next
      - name: Run Component Testing
        uses: cypress-io/github-action@v5
        with:
          component: true
          config-file: cypress.config.ts
